// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbA_qRqLveTCMZWMqaCqMEiJDeN0tWoZ8',
    appId: '1:709590244534:web:bcd29ce79569b59d225a17',
    messagingSenderId: '709590244534',
    projectId: 'chatapplication-4c8a7',
    authDomain: 'chatapplication-4c8a7.firebaseapp.com',
    storageBucket: 'chatapplication-4c8a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIQ5_v5Ul4TCXOEHmKuUn5APoWWbc4efI',
    appId: '1:709590244534:android:d79d2dfe33ca5248225a17',
    messagingSenderId: '709590244534',
    projectId: 'chatapplication-4c8a7',
    storageBucket: 'chatapplication-4c8a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN0qpgQJjOzDlCDucC-2t5I5MgDmiV68w',
    appId: '1:709590244534:ios:1b546b4e03b0906c225a17',
    messagingSenderId: '709590244534',
    projectId: 'chatapplication-4c8a7',
    storageBucket: 'chatapplication-4c8a7.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN0qpgQJjOzDlCDucC-2t5I5MgDmiV68w',
    appId: '1:709590244534:ios:1b546b4e03b0906c225a17',
    messagingSenderId: '709590244534',
    projectId: 'chatapplication-4c8a7',
    storageBucket: 'chatapplication-4c8a7.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );
}
